// src/aot/build.c
//
// Compile pipeline for the Bend2-style AOT.  Driven from
// thvm_aot_compile_to_dylib (this file) and called from the WL
// bridge in wl/THVMLink/CSource/thvmlink.c.
//
// Pipeline:
//
//   1. Call thvm_aot_emit_program(def_id, name) to get the C source
//      for the def's entry + cont fns + dispatch + register.
//
//   2. Wrap the source: prepend `#include "<repo>/src/thvm.c"` so
//      the dylib carries its own copy of the thvm runtime (heap,
//      DEFS, dispatch helpers, etc.) -- no host-side OPS function-
//      pointer ABI needed.  Append a known-named entry point:
//
//        u64 aot_program_<name>_run(u64 input_term);
//
//      which thvm_init's a fresh runtime, registers the program,
//      runs aot_run_serial with the input as args[0], returns the
//      result Term as a u64.
//
//   3. Write to /tmp/aot_<name>_<hash>.c so cache-by-content works
//      across calls (same source -> same dylib path -> skip clang).
//
//   4. Invoke clang -O2 -dynamiclib -fPIC ... to produce the
//      dylib alongside the .c.  Return the dylib path string
//      (caller must free).
//
// For NUM-result programs (count, tree_sum, fib -- anything that
// reduces to a scalar) the returned Term is self-contained: the
// caller can extract term_val(t) as the answer.  For programs
// that return CTRs, the Term references the dylib's heap and the
// host can't decode without a marshalling protocol -- that lands
// later if needed.
//
// Iter E1 (this iter): the compile pipeline + a new test that
// emits, compiles, and inspects the dylib path / file size.  Iter
// E2 adds the dlopen + dlsym + run side; iter E3 adds the WL
// TAOTCompile + TAOTRun surface on top.

#ifndef THVM_AOT_BUILD_INCLUDED
#define THVM_AOT_BUILD_INCLUDED

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <sys/stat.h>
#include <dlfcn.h>

// Embedded thvm.c source (flattened: all our `#include "..."`
// directives resolved, system `<...>` headers preserved).  Defined
// in build/thvm_runtime_blob.c (generated by tools/inline_includes.py
// + tools/embed_blob.py at paclet build time).  AOT compile reads
// this content into /tmp/aot_*.c and clang-compiles it together
// with the per-program emit -- the runtime's static-inline helpers
// must be in the SAME translation unit to be reachable, so linking
// against a precompiled .o doesn't work without a big refactor of
// `fn = static inline` → `extern`.  Per-call compile is ~3-4 sec
// uncached; cache-by-content hits skip the compile entirely.
extern const char     thvm_runtime_src[];
extern const uint64_t thvm_runtime_src_len;

// FNV-1a 64-bit -- cheap content hash for cache-by-content paths.
static u64 aot_fnv1a64(const char *s) {
  u64 h = 0xcbf29ce484222325ULL;
  for (; *s; s++) {
    h ^= (u8)*s;
    h *= 0x100000001b3ULL;
  }
  return h;
}

// Wrap emit source with the dylib boilerplate.  The flattened
// runtime source is embedded into the wrapper at the top so the
// per-program emit's references to static-inline helpers
// (term_new, heap_alloc, aot_make_value, ...) resolve in the
// same translation unit.  Per-call compile is ~3-4 sec uncached;
// the build.c cache-by-content key catches repeats.
//
// Caller frees the returned malloc'd string.
static char *aot_wrap_emit_for_dylib(const char *emit_src,
                                     const char *name) {
  size_t cap = (size_t)thvm_runtime_src_len + strlen(emit_src)
             + strlen(name) * 8 + 8192;
  char *out = (char *)malloc(cap);
  if (!out) return NULL;

  int n = snprintf(out, cap,
    "// auto-wrapped by thvm_aot_compile_to_dylib for \"%s\"\n"
    "//\n"
    "// Shared-heap dylib (Phase 6 iter A + X): the thvm runtime\n"
    "// (src/thvm.c flattened) is INLINED at the top of this file.\n"
    "// Static-inline helpers must live in the same translation\n"
    "// unit to be reachable from the per-program emit, so linking\n"
    "// against a precompiled .o would require an extern-ifying\n"
    "// refactor of `fn = static inline` -- deferred.  At run()\n"
    "// entry the host's CURRENT_CTX is wired in so every helper\n"
    "// operates on the SAME heap, DEFS, ITRS, callback tables as\n"
    "// the host.\n"
    "//\n"
    "// Host calls: aot_program_%s_run(host_ctx, input_term).\n"
    "\n"
    "// === BEGIN inlined thvm runtime ===\n",
    name, name);

  if (n < 0 || (size_t)n >= cap) { free(out); return NULL; }
  size_t pos = (size_t)n;

  // Copy the embedded runtime source verbatim.
  memcpy(out + pos, thvm_runtime_src, (size_t)thvm_runtime_src_len);
  pos += (size_t)thvm_runtime_src_len;
  const char *runtime_end = "\n// === END inlined thvm runtime ===\n\n";
  size_t runtime_end_len = strlen(runtime_end);
  memcpy(out + pos, runtime_end, runtime_end_len);
  pos += runtime_end_len;
  out[pos] = '\0';

  // Append the emit source verbatim.
  size_t emit_len = strlen(emit_src);
  if (pos + emit_len + 1 >= cap) {
    cap = pos + emit_len + 4096;
    char *nb = (char *)realloc(out, cap);
    if (!nb) { free(out); return NULL; }
    out = nb;
  }
  memcpy(out + pos, emit_src, emit_len);
  pos += emit_len;
  out[pos] = '\0';

  // Append the run entry.  Returns the result Term as u64; caller
  // dlsym's "aot_program_<name>_run" and invokes with the host's
  // CURRENT_CTX as the first arg (Phase 6 iter A: shared heap).
  int m = snprintf(out + pos, cap - pos,
    "\n"
    "u64 aot_program_%s_run(void *host_ctx, u64 in0, u64 in1, u64 in2, u64 in3) {\n"
    "  // Point this dylib's CURRENT_CTX pointer at the host's\n"
    "  // TContext struct.  All subsequent runtime calls inline'd\n"
    "  // from src/thvm.c read/write through CURRENT_CTX, so they\n"
    "  // operate on the host's HEAP / DEFS / ITRS / callbacks /\n"
    "  // device buffers.  No thvm_init -- that would re-zero the\n"
    "  // host's state.\n"
    "  CURRENT_CTX = (TContext *)host_ctx;\n"
    "  // Bind the calling thread's TLS WNF spine to the shared\n"
    "  // ctx's wnf_state.  Required because the dispatch fast-path\n"
    "  // calls wnf() on non-WHNF inputs (TAG_OP2/TAG_REF/etc.) --\n"
    "  // wnf reads CURRENT_WNF_STATE which is per-thread TLS.  The\n"
    "  // dylib has its own TLS slot, zero-initialised; bind it now.\n"
    "  CURRENT_WNF_STATE = &CURRENT_CTX->wnf_state;\n"
    "  // Populate this dylib's static PRIM_TABLE with the core\n"
    "  // primitives (THVM_PRIM_PRI, etc.).  The host already did\n"
    "  // this during its own thvm_init, but the dylib's #include\n"
    "  // \"src/thvm.c\" gave it a SEPARATE static PRIM_TABLE -- so\n"
    "  // a TPri redex inside the AOT'd code would otherwise miss\n"
    "  // the core PRI prim and refuse to fire.  Call once per run;\n"
    "  // re-registration is idempotent (same C function pointers).\n"
    "  thvm_register_core_prims();\n"
    "  AotProgram p;\n"
    "  aot_program_%s_register(&p);\n"
    "  AotTask root = aot_make_task(FN_%s, AOT_RET_ROOT,\n"
    "                                (Term)in0, (Term)in1, (Term)in2, (Term)in3);\n"
    "  Term r = aot_run_serial(&p, root);\n"
    "  return (u64)r;\n"
    "}\n",
    name, name, name);

  if (m < 0 || (size_t)m >= cap - pos) { free(out); return NULL; }
  return out;
}

// Compile the def at `def_id` (named `name`) into a dylib at the
// returned path (caller frees).  Returns NULL on any failure;
// errors go to stderr.  Cache hit (file already exists at the
// computed path) skips the clang invocation.
fn char *thvm_aot_compile_to_dylib(u32 def_id, const char *name) {
  if (def_id >= DEFS_CAP || name == NULL) return NULL;
  if (DEFS[def_id] == 0) return NULL;

  char *src = thvm_aot_emit_program(def_id, name);
  if (!src) return NULL;

  char *wrapped = aot_wrap_emit_for_dylib(src, name);
  free(src);
  if (!wrapped) return NULL;

  // Cache key: name + wrapped-source content hash.  Putting the
  // hash in the filename lets us skip clang when the same source
  // would have produced the same dylib.
  u64 hash = aot_fnv1a64(wrapped);

  char src_path[512], dyl_path[512];
  snprintf(src_path, sizeof src_path,
           "/tmp/aot_%s_%016llx.c", name, (unsigned long long)hash);
  snprintf(dyl_path, sizeof dyl_path,
           "/tmp/aot_%s_%016llx.dylib", name, (unsigned long long)hash);

  // Cache hit?
  struct stat st;
  if (stat(dyl_path, &st) == 0) {
    free(wrapped);
    return strdup(dyl_path);
  }

  FILE *f = fopen(src_path, "w");
  if (!f) { free(wrapped); return NULL; }
  fputs(wrapped, f);
  fclose(f);
  free(wrapped);

  // -dynamiclib (macOS) or -shared (Linux) -- pick from the build.
  // -DTHVM_HAS_WL_BRIDGE skips the weak default of
  //   thvm_pri_wl_invoke_returning() that prims_core.c provides for
  //   standalone builds.  The dylib then has an UNDEFINED reference
  //   to the symbol; -undefined dynamic_lookup defers resolution
  //   until dlopen time, where it resolves against any module
  //   already loaded into the host process (THVMLink.dylib for the
  //   WL path, the test binary for C tests).  This lets PRI
  //   redexes inside AOT'd code call into host-registered WL
  //   callbacks naturally -- without it, the dylib calls its own
  //   no-op weak copy and the callback never fires.
#ifdef __APPLE__
  const char *dylib_flags = "-dynamiclib -framework Accelerate "
                             "-undefined dynamic_lookup";
#else
  const char *dylib_flags = "-shared "
                             "-Wl,--unresolved-symbols=ignore-in-object-files";
#endif

  char cmd[2048];
  snprintf(cmd, sizeof cmd,
    "clang -O2 -fPIC -std=c11 -Wno-everything "
    "-DACCELERATE_NEW_LAPACK -DTHVM_HAS_WL_BRIDGE %s "
    "-o '%s' '%s' 2>&1",
    dylib_flags, dyl_path, src_path);

  FILE *p = popen(cmd, "r");
  if (!p) return NULL;
  char line[1024];
  int saw_error = 0;
  while (fgets(line, sizeof line, p) != NULL) {
    if (strstr(line, "error:") != NULL) {
      fprintf(stderr, "thvm_aot_compile_to_dylib: clang: %s", line);
      saw_error = 1;
    }
  }
  int rc = pclose(p);
  if (rc != 0 || saw_error) {
    fprintf(stderr,
      "thvm_aot_compile_to_dylib: clang failed (rc=%d) for %s\n",
      rc, src_path);
    return NULL;
  }

  return strdup(dyl_path);
}

// Load an AOT-compiled dylib (returned by thvm_aot_compile_to_dylib),
// resolve its `aot_program_<name>_run(u64 input) -> u64` entry, and
// invoke it with the given input Term.  Returns the result Term as
// u64 on success, 0 on any failure (dlopen / dlsym / etc.).
//
// Caller passes the same `name` used at compile time.  We can't
// derive it from the path because cache filenames include a hash,
// not the name in a form we can parse back.
//
// The dylib is leaked (no dlclose).  Calling this in a tight loop
// is fine because dlopen on the same path returns the same handle
// (refcounted); cumulative cost grows by handle-table entries only.
// A future API can return the handle for explicit dlclose if a
// caller needs to unload (e.g., to swap implementations).
// Run with up to 4 input Terms.  Extra args are 0 for defs that
// take fewer (the dispatch ignores them).  WL TAOTRun bridges
// here with a list of Terms; C tests pass 0s for trailing slots.
fn u64 thvm_aot_load_and_run4(const char *dylib_path, const char *name,
                               u64 in0, u64 in1, u64 in2, u64 in3) {
  if (!dylib_path || !name) return 0;

  void *h = dlopen(dylib_path, RTLD_NOW | RTLD_LOCAL);
  if (!h) {
    fprintf(stderr, "thvm_aot_load_and_run: dlopen %s failed: %s\n",
            dylib_path, dlerror());
    return 0;
  }

  char sym[256];
  snprintf(sym, sizeof sym, "aot_program_%s_run", name);
  typedef u64 (*RunFn)(void *, u64, u64, u64, u64);
  RunFn run = (RunFn)dlsym(h, sym);
  if (!run) {
    fprintf(stderr, "thvm_aot_load_and_run: dlsym %s failed: %s\n",
            sym, dlerror());
    dlclose(h);
    return 0;
  }

  // Pass the host's CURRENT_CTX so the dylib reuses the host's
  // HEAP / DEFS / callbacks / device buffers (Phase 6 iter A).
  return run((void *)CURRENT_CTX, in0, in1, in2, in3);
}

// Backwards-compat 1-arg shim.  Existing C tests + the bare-Integer
// WL bridge entry use this; new multi-arg path goes through
// thvm_aot_load_and_run4 directly.
fn u64 thvm_aot_load_and_run(const char *dylib_path, const char *name,
                              u64 input) {
  return thvm_aot_load_and_run4(dylib_path, name, input, 0, 0, 0);
}

#endif  // THVM_AOT_BUILD_INCLUDED
