// aot/emit.c -- walk a TDef'd body and emit equivalent C source for
// the AOT layer.  Phase 0: scope to constants and trivial lambdas
// so the file structure + WL surface land first; the rest of the
// patterns (MAT chain, CTR destructure, OP2, DUP) come in
// follow-up commits.
//
// Output shape per def `@name`:
//
//   static Term aot_emitted_<name>_direct(...) {
//     // walked body
//   }
//   static Term aot_emitted_<name>(Term *stack, u32 *sp, u32 base) {
//     // pop expected args; call _direct.
//   }
//   void aot_program_emit_<name>_register(u32 def_slot) {
//     aot_register(def_slot, aot_emitted_<name>);
//   }
//
// The emitted source is meant to be #include'd into the same TU as
// the runtime (matching the existing src/aot/programs/<name>.c
// convention).  A future src/aot/build.c will write the buffer to
// disk, kick off clang, dlopen, dlsym -- but that path needs an ABI
// split first (the runtime's helpers are `static inline`, so a
// dlopen'd dylib can't call them).  Phase 0 just exposes
// thvm_aot_emit_def() to produce the string; users put it under
// src/aot/programs/ and rebuild.

#define AOT_EMIT_CAP    (1u << 16)   // 64 KB initial output buffer

typedef struct {
    char *buf;
    u32   len;
    u32   cap;
} AotEmitBuf;

static void aot_emit_init(AotEmitBuf *b) {
    b->buf = (char *)malloc(AOT_EMIT_CAP);
    b->len = 0;
    b->cap = AOT_EMIT_CAP;
    if (b->buf) b->buf[0] = '\0';
}

static void aot_emit_grow(AotEmitBuf *b, u32 need) {
    while (b->cap - b->len < need) {
        u32 new_cap = b->cap * 2;
        char *nb = (char *)realloc(b->buf, new_cap);
        if (!nb) {
            // Out of memory -- truncate.  Caller checks b->len for
            // whether the emit went OK.
            return;
        }
        b->buf = nb;
        b->cap = new_cap;
    }
}

static void aot_emit_str(AotEmitBuf *b, const char *s) {
    u32 n = (u32)strlen(s);
    aot_emit_grow(b, n + 1);
    memcpy(b->buf + b->len, s, n);
    b->len += n;
    b->buf[b->len] = '\0';
}

static void aot_emit_fmt(AotEmitBuf *b, const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    char tmp[1024];
    int n = vsnprintf(tmp, sizeof(tmp), fmt, ap);
    va_end(ap);
    if (n < 0) return;
    aot_emit_str(b, tmp);
}

// Sanitize a name (book def name string isn't tracked yet; we use
// the integer slot directly as a stable id).  Keeps the emitted
// symbol unambiguous and ASCII-safe.
static void aot_emit_def_id_str(AotEmitBuf *b, u32 def_id) {
    aot_emit_fmt(b, "%u", def_id);
}

// === Body walker =====================================================
//
// Phase 0 supports just two body shapes: a bare TAG_NUM (constant
// def) and a single TLam over a TVAR (identity).  Anything else
// returns a "/* unsupported */" comment so the caller knows to fall
// back to a hand-coded program.

static int aot_emit_body(AotEmitBuf *b, Term body) {
    u8 tag = term_tag(body);
    switch (tag) {
      case TAG_NUM: {
        u32 ext = term_ext(body);
        u32 val = (u32)term_val(body);
        aot_emit_fmt(b, "  return term_new(0, TAG_NUM, %u, %u);\n", ext, val);
        return 1;
      }
      case TAG_LAM: {
        // Identity-style: TLam[x, x] -> the body cell at lam_loc
        // holds a TAG_VAR pointing back at lam_loc.  Pop one APP
        // arg from the spine and return it.
        u64 lam_loc = term_val(body);
        Term inner  = book_read(lam_loc);
        if (term_tag(inner) == TAG_VAR && term_val(inner) == lam_loc) {
            aot_emit_str(b,
                "  Term arg = aot_pop_app_arg(stack, sp, base);\n"
                "  if (arg == 0) return aot_fallback(def_slot);\n"
                "  ITRS++;   // APP-LAM\n"
                "  return arg;\n");
            return 1;
        }
        aot_emit_str(b, "  /* unsupported: TLam with non-identity body */\n"
                        "  return aot_fallback(def_slot);\n");
        return 0;
      }
      default: {
        aot_emit_fmt(b, "  /* unsupported tag: %u */\n"
                        "  return aot_fallback(def_slot);\n", tag);
        return 0;
      }
    }
}

// === Public entry ====================================================
//
// thvm_aot_emit_def(def_id) returns a malloc'd null-terminated C
// source string.  Caller frees.  Returns NULL if the def slot is
// empty.
//
// The emitted code captures `def_slot` (the integer id) by closure:
// inside _direct / the stack entry, calls to aot_fallback(def_slot)
// route to the right book template at the runtime's discretion.

fn char *thvm_aot_emit_def(u32 def_id) {
    if (def_id >= DEFS_CAP) return NULL;
    Term root = DEFS[def_id];
    if (root == 0) return NULL;

    AotEmitBuf b;
    aot_emit_init(&b);
    if (!b.buf) return NULL;

    aot_emit_str(&b,
        "// aot/emitted/<def_id>.c -- generated by thvm_aot_emit_def.\n"
        "// Phase 0: minimal coverage (constants, identity).\n"
        "// Drop this under src/aot/programs/ and add an #include in src/thvm.c.\n"
        "\n");

    // _direct entry: the AOT body.  Captures def_slot via a static.
    aot_emit_str(&b, "static u32 G_EMIT_DEF_SLOT_");
    aot_emit_def_id_str(&b, def_id);
    aot_emit_str(&b, " = (u32)-1;\n");
    aot_emit_str(&b, "#define def_slot G_EMIT_DEF_SLOT_");
    aot_emit_def_id_str(&b, def_id);
    aot_emit_str(&b, "\n\n");

    aot_emit_str(&b, "static Term aot_emitted_");
    aot_emit_def_id_str(&b, def_id);
    aot_emit_str(&b, "(Term *stack, u32 *sp, u32 base) {\n");
    aot_emit_body(&b, root);
    aot_emit_str(&b, "}\n\n");

    // Registration helper.
    aot_emit_str(&b, "fn void aot_program_emit_");
    aot_emit_def_id_str(&b, def_id);
    aot_emit_str(&b, "_register(u32 slot) {\n"
                     "  def_slot = slot;\n"
                     "  aot_register(slot, aot_emitted_");
    aot_emit_def_id_str(&b, def_id);
    aot_emit_str(&b, ");\n}\n"
                     "#undef def_slot\n");

    return b.buf;
}
