// src/aot/resolve.c
//
// Walk a freshly-computed value up the continuation tree.
//
// When a worker dispatches an AotTask and gets back AOT_R_VALUE
// (the task returned a final answer), it calls aot_resolve(ret, val).
// What happens next depends on `ret`:
//
//   ret == AOT_RET_ROOT
//       This task's value IS the program's answer.  Stash it in
//       `program->result` and signal `program->done` so the worker
//       loop in src/aot/worker.c (next iter) can break out.
//
//   ret encodes a slot in some parent cont cell
//       Write the value into the slot via aot_write_slot.  If we
//       were the LAST child to land (write_slot returned 1), fire
//       the parent cont and dispatch IT.  That dispatch may itself
//       return another AOT_R_VALUE -- loop and resolve that one
//       upward too (tail-chaining without recursion, exactly what
//       Bend2 does at TinyHVM/resources/gists/par_tree_sum_bend2_compiled.c:491).
//
//       Or it returns AOT_R_SPLIT / AOT_R_CALL -- enqueue the
//       resulting child tasks into the worker's output buffer for
//       the seed/work loop to pick up.
//
// The output-buffer pointer + count are passed in so this file
// stays decoupled from the worker's queue implementation.  Atomic
// fetch-add on `*out_n` is the single coordination point with
// other workers writing the same buffer in parallel.
//
// `program` carries the dispatch function pointer + result/done
// state.  Defined in task.h so the worker can fill it once at
// program-start and resolve / fire / worker all share the view.

#include "task.h"

// Forward decl of the worker's program context (defined in worker.c).
// dispatch() is the program's emitted "dispatch by fn id" switch --
// hand-written in the Phase 1 tree_sum test, auto-generated by emit
// in Phase 2.
struct AotProgram;
typedef AotResult (*AotDispatchFn)(struct AotProgram *p, AotTask *task);

typedef struct AotProgram {
  AotDispatchFn  dispatch;
  // Filled by aot_resolve when a task with ret == AOT_RET_ROOT
  // finishes.  Worker loop watches `done` and stops once it flips.
  // _Atomic u32 + atomic_*_explicit matches src/wnf/pool.c's style;
  // mixing with __atomic_* GCC builtins fails to compile here.
  Term           result;
  _Atomic u32    done;
  // Workers share one AotProgram instance during a run -- callbacks
  // (dispatch, continuations) reach back to per-program state through
  // the program pointer threaded through aot_resolve / dispatch.
} AotProgram;

// Resolve loop.  Tail-chains R_VALUE results through cont firings
// without recursion -- one call to aot_resolve handles an arbitrary
// chain of "value lands -> last writer -> fire cont -> get value
// back -> last writer again -> ..."  until either:
//
//   - we hit AOT_RET_ROOT (program done)
//   - we're not the last writer for some cont (other branch still
//     pending; some other worker will fire when it lands)
//   - the fired cont returns R_SPLIT or R_CALL (push children to
//     worker queue, return so the worker can pick them up)
// out_n is a PLAIN counter (not atomic): each worker passes its
// own WorkerOut.n in the parallel path, and the serial path passes
// a local uint.  Atomicity used to be in this signature back when
// every worker pushed directly into the global queue; iter B moved
// that contention to a per-worker batched flush so this counter is
// always thread-local.
fn void aot_resolve(AotProgram *program,
                    u32 ret, Term val,
                    AotTask *out, u32 *out_n) {
  while (1) {
    if (ret == AOT_RET_ROOT) {
      program->result = val;
      atomic_store_explicit(&program->done, 1, memory_order_release);
      return;
    }
    // Not root -- write into the parent's cell.  If we're not the
    // last writer, the OTHER child is still pending; whoever resolves
    // it last will fire the cont.  We're done here.
    if (!aot_write_slot(ret, val)) return;

    // We were the last writer.  Fire the cont, dispatch it.
    u32 dp = aot_dec_dp(ret);
    AotTask t = aot_fire_cont(dp);
    AotResult r = program->dispatch(program, &t);

    if (r.tag == AOT_R_VALUE) {
      // The cont returned a value too -- chain upward.
      val = r.val;
      ret = t.ret;
      continue;
    }
    if (r.tag == AOT_R_SPLIT) {
      u32 i = *out_n;
      out[i + 0] = r.t0;
      out[i + 1] = r.t1;
      *out_n = i + 2;
      return;
    }
    // AOT_R_CALL
    u32 i = *out_n;
    out[i] = r.t0;
    *out_n = i + 1;
    return;
  }
}
