// schedule/tile.c -- im2col-fused Conv2D shape classifier.
//
// Matmul shapes are canonicalised as MUL+REDUCE+OPT_TC UOp DAG nodes by
// the unified rangeify pass and lifted into the kernel root by
// kernel_lift_to_uop.  Downstream consumers (BLAS GEMM/DOT/GEMV dispatch, apply_opt KOP_TC
// gate, propose KOP_TC tile-size proposer) read shape facts from
// ke->cached_lift.store_root via uop_dag_classify_matmul_shape /
// uop_dag_classify_dot_shape / uop_dag_classify_gemv_shape
// (src/uop/dag_scan.c).

#define TILE_REDUCE_KIND(arg)  (((arg) >> 24) & 0xFFu)

static u32 tile_isqrt_exact(u32 x) {
  for (u32 r = 1; r <= x / r; r++) {
    if (r * r == x) {
      return r;
    }
  }
  return 0;
}

static u32 tile_conv2d_threads_from_opts(KernelEntry const *ke) {
  u32 threads = 256;
  u32 n_app = tile_anno_applied_opts_count(ke);
  KOpt const *opts = tile_anno_applied_opts(ke);
  for (u32 i = 0; i < n_app; i++) {
    KOpt opt = opts[i];
    if (opt.op == KOP_LOCAL && opt.arg > 0 && opt.arg <= 256) {
      threads = opt.arg;
    }
  }
  return threads;
}

static u32 tile_conv2d_outputs_from_opts(KernelEntry const *ke) {
  u32 outputs = 1;
  u32 n_app = tile_anno_applied_opts_count(ke);
  KOpt const *opts = tile_anno_applied_opts(ke);
  for (u32 i = 0; i < n_app; i++) {
    KOpt opt = opts[i];
    if (opt.op == KOP_UPCAST && opt.arg > 0 && opt.arg <= 16) {
      outputs = opt.arg;
    }
  }
  return outputs;
}

static u32 tile_conv2d_reduce_unroll_from_opts(KernelEntry const *ke,
                                               u32 reduce_extent) {
  u32 unroll = 1;
  if (reduce_extent == 0) return unroll;
  u32 n_app = tile_anno_applied_opts_count(ke);
  KOpt const *opts = tile_anno_applied_opts(ke);
  for (u32 i = 0; i < n_app; i++) {
    KOpt opt = opts[i];
    if (opt.op == KOP_UNROLL && opt.arg > 1 && opt.arg <= 16
        && reduce_extent % opt.arg == 0) {
      unroll = opt.arg;
    }
  }
  return unroll;
}

// Coverage counter for the conv2d-flat DAG classifier.  Fires when
// `cached_lift.store_root != 0` AND
// `uop_dag_classify_conv2d_flat_shape` accepts.
static u64 TILE_CONV2D_FLAT_DAG    = 0;

fn u64 tile_conv2d_flat_dag_count   (void) { return TILE_CONV2D_FLAT_DAG; }

static int tile_analyze_conv2d_flat_impl(KernelEntry const *ke,
                                         TileConv2DInfo *out,
                                         int allow_cin1) {
  if (ke == NULL || out == NULL || ke->n_inputs < 2) {
    return 0;
  }
  if (ke->input_dtypes[0] != DT_FP32 || ke->output_dtype != DT_FP32) {
    return 0;
  }
  for (u32 i = 1; i < ke->n_inputs; i++) {
    if (ke->input_dtypes[i] != DT_FP32) {
      return 0;
    }
  }

  // DAG-side structural gate: classify the lifted UOp DAG.  Materialize
  // always populates cached_lift.store_root on emitted kernels.
  if (ke->cached_lift.store_root == 0) return 0;
  if (!uop_dag_classify_conv2d_flat_shape(ke->cached_lift.store_root)) {
    return 0;
  }
  TILE_CONV2D_FLAT_DAG++;

  // Try the DAG-side full-shape extractor first.  When the lift
  // took the single-input path AND the address tree wasn't
  // degenerated by the simplifier, the extractor recovers every
  // shape field from the W and X INDEX_E.addr trees.  Multi-input
  // conv (IWHERE chain) and degenerate kh==kw==1 still fall through
  // to the input_views reader below.
  if (ke->cached_lift.store_root != 0 && ke->n_inputs == 2) {
    Term sroot = ke->cached_lift.store_root;
    if (term_tag(sroot) == TAG_UOP && term_ext(sroot) == UOP_STORE) {
      Term value = heap_read(term_val(sroot) + 2);
      if (term_tag(value) == TAG_UOP && term_ext(value) == UOP_OPT) {
        value = uop_opt_target(value);
      }
      if (term_tag(value) == TAG_UOP && term_ext(value) == UOP_REDUCE) {
        Term mul = heap_read(term_val(value) + 0);
        if (term_tag(mul) == TAG_UOP && term_ext(mul) == UOP_MUL) {
          Term ldW = heap_read(term_val(mul) + 0);
          Term ldX = heap_read(term_val(mul) + 1);
          if (term_tag(ldW) == TAG_UOP && term_ext(ldW) == UOP_INDEX_E
              && term_tag(ldX) == TAG_UOP && term_ext(ldX) == UOP_INDEX_E) {
            Term addr_w = heap_read(term_val(ldW) + 1);
            Term addr_x = heap_read(term_val(ldX) + 1);
            UopDagConv2dFlatShape ds = {0};
            if (uop_dag_extract_conv2d_flat_shape(addr_w, addr_x, &ds)
                && (ds.c_in > 1 || allow_cin1)
                && ds.c_out * ds.patches == ke->output_numel) {
              // Cross-check output_shape too -- belt-and-braces on the
              // c_out * patches == output_numel check above.
              int out_flat = ke->output_shape.ndim == 2
                          && ke->output_shape.dims[0] == ds.c_out
                          && ke->output_shape.dims[1] == ds.patches;
              int out_chw  = ke->output_shape.ndim == 3
                          && ke->output_shape.dims[0] == ds.c_out
                          && ke->output_shape.dims[1] == ds.h_out
                          && ke->output_shape.dims[2] == ds.w_out;
              if (out_flat || out_chw) {
                memset(out, 0, sizeof(TileConv2DInfo));
                out->dtype     = DT_FP32;
                out->w_input   = 0;
                out->x_input   = 1;
                out->patch_input_base  = 0;
                out->patch_input_count = 0;
                out->c_out     = ds.c_out;
                out->c_in      = ds.c_in;
                out->h         = ds.h_out + ds.kh - 1;
                out->w         = ds.w_out + ds.kw - 1;
                out->kh        = ds.kh;
                out->kw        = ds.kw;
                out->h_out     = ds.h_out;
                out->w_out     = ds.w_out;
                out->batch     = ds.batch;
                out->patches   = ds.patches;
                out->spatial_patches = ds.spatial_patches;
                out->w_offset  = ds.w_offset;
                out->w_stride0 = ds.w_stride0;
                out->w_stride1 = ds.w_stride1;
                out->x_offset  = ds.x_offset;
                out->x_stride_b = ds.x_stride_b;
                out->x_stride0 = ds.x_stride0;
                out->x_stride1 = ds.x_stride1;
                out->x_stride2 = ds.x_stride2;
                out->threads   = tile_conv2d_threads_from_opts(ke);
                out->outputs_per_thread = tile_conv2d_outputs_from_opts(ke);
                u32 k_total = ds.c_in * ds.kh * ds.kw;
                out->reduce_unroll = tile_conv2d_reduce_unroll_from_opts(ke,
                                                                         k_total);
                return 1;
              }
            }
          }
        }
      }
    }
  }

  // DAG-side extractor declined (multi-input, degenerate, or
  // non-canonical address shape).  Fall back to the input_views[]
  // reader.
  if (ke->input_views == NULL) return 0;

  View const *wv = &ke->input_views[0];
  if (wv->shape.ndim != 3
      || (ke->output_shape.ndim != 2 && ke->output_shape.ndim != 3)) {
    return 0;
  }
  u32 c_out = wv->shape.dims[0];
  u32 k     = wv->shape.dims[1];
  u32 p     = wv->shape.dims[2];
  u32 batch = 1;
  u32 c_in = 0, h = 0, w = 0;
  i32 x_offset = 0;
  i32 x_stride_b = 0;
  i32 x_stride0 = 0, x_stride1 = 0, x_stride2 = 0;
  u32 patch_base = 0, patch_count = 0;
  if (c_out == 0 || k == 0 || p == 0) {
    return 0;
  }
  u32 kh = 0, kw = 0, h_out = 0, w_out = 0, spatial_patches = 0;
  int direct_x = ke->n_inputs == 2;
  if (direct_x) {
    View const *xv = &ke->input_views[1];
    if (xv->shape.ndim != 3 && xv->shape.ndim != 4) {
      return 0;
    }
    if (xv->shape.ndim == 3) {
      c_in      = xv->shape.dims[0];
      h         = xv->shape.dims[1];
      w         = xv->shape.dims[2];
      x_offset  = xv->offset;
      x_stride0 = xv->strides[0];
      x_stride1 = xv->strides[1];
      x_stride2 = xv->strides[2];
    } else {
      batch      = xv->shape.dims[0];
      c_in       = xv->shape.dims[1];
      h          = xv->shape.dims[2];
      w          = xv->shape.dims[3];
      x_offset   = xv->offset;
      x_stride_b = xv->strides[0];
      x_stride0  = xv->strides[1];
      x_stride1  = xv->strides[2];
      x_stride2  = xv->strides[3];
    }
    if (c_in == 0 || (c_in == 1 && !allow_cin1) || k % c_in != 0) {
      return 0;
    }
    u32 k_spatial = k / c_in;
    kh = tile_isqrt_exact(k_spatial);
    if (kh == 0) {
      return 0;
    }
    kw = kh;
    if (h < kh || w < kw) {
      return 0;
    }
    h_out = h - kh + 1;
    w_out = w - kw + 1;
    spatial_patches = h_out * w_out;
  } else {
    c_in = 1;
    kh = tile_isqrt_exact(k);
    if (kh == 0) {
      return 0;
    }
    kw = kh;
    patch_base = 1;
    patch_count = k;
    if (ke->n_inputs != 1 + patch_count) {
      return 0;
    }
    View const *pv0 = &ke->input_views[patch_base];
    if (pv0->shape.ndim == 3) {
      if (pv0->shape.dims[0] != 1) {
        return 0;
      }
      h_out = pv0->shape.dims[1];
      w_out = pv0->shape.dims[2];
    } else if (pv0->shape.ndim == 4) {
      if (pv0->shape.dims[0] != 1) {
        return 0;
      }
      batch = pv0->shape.dims[1];
      h_out = pv0->shape.dims[2];
      w_out = pv0->shape.dims[3];
    } else {
      return 0;
    }
    for (u32 i = 0; i < patch_count; i++) {
      View const *pv = &ke->input_views[patch_base + i];
      if (pv->shape.ndim != pv0->shape.ndim) {
        return 0;
      }
      if (pv->shape.ndim == 3) {
        if (pv->shape.dims[0] != 1 || pv->shape.dims[1] != h_out
            || pv->shape.dims[2] != w_out) {
          return 0;
        }
      } else if (pv->shape.dims[0] != 1 || pv->shape.dims[1] != batch
          || pv->shape.dims[2] != h_out || pv->shape.dims[3] != w_out) {
        return 0;
      }
    }
    h = h_out + kh - 1;
    w = w_out + kw - 1;
    spatial_patches = h_out * w_out;
  }
  if (kh == 0) {
    return 0;
  }
  if (batch == 0 || spatial_patches == 0 || batch * spatial_patches != p) {
    return 0;
  }
  int output_flat = ke->output_shape.ndim == 2
                 && ke->output_shape.dims[0] == c_out
                 && ke->output_shape.dims[1] == p;
  int output_chw = ke->output_shape.ndim == 3
                && ke->output_shape.dims[0] == c_out
                && ke->output_shape.dims[1] == h_out
                && ke->output_shape.dims[2] == w_out;
  if ((!output_flat && !output_chw) || ke->output_numel != c_out * p) {
    return 0;
  }
  if (wv->strides[2] != 0) {
    return 0;
  }

  memset(out, 0, sizeof(TileConv2DInfo));
  out->dtype     = DT_FP32;
  out->w_input   = 0;
  out->x_input   = direct_x ? 1 : 0;
  out->patch_input_base  = patch_base;
  out->patch_input_count = patch_count;
  out->c_out     = c_out;
  out->c_in      = c_in;
  out->h         = h;
  out->w         = w;
  out->kh        = kh;
  out->kw        = kw;
  out->h_out     = h_out;
  out->w_out     = w_out;
  out->batch     = batch;
  out->patches   = p;
  out->spatial_patches = spatial_patches;
  out->w_offset  = wv->offset;
  out->w_stride0 = wv->strides[0];
  out->w_stride1 = wv->strides[1];
  out->x_offset  = x_offset;
  out->x_stride_b = x_stride_b;
  out->x_stride0 = x_stride0;
  out->x_stride1 = x_stride1;
  out->x_stride2 = x_stride2;
  out->threads   = tile_conv2d_threads_from_opts(ke);
  out->outputs_per_thread = tile_conv2d_outputs_from_opts(ke);
  out->reduce_unroll = tile_conv2d_reduce_unroll_from_opts(ke, k);
  return 1;
}

int tile_analyze_conv2d_flat(KernelEntry const *ke, TileConv2DInfo *out) {
  return tile_analyze_conv2d_flat_impl(ke, out, 0);
}

int tile_rejects_conv2d_flat_cin1(KernelEntry const *ke) {
  TileConv2DInfo conv;
  if (!tile_analyze_conv2d_flat_impl(ke, &conv, 1)) {
    return 0;
  }
  return conv.c_in == 1 && conv.patch_input_count == 0;
}



