// docs/aot_emitted_examples/identity_lam.c
//
// Identity (id : a -> a).  Smallest possible AOT'd def.
// 
// Shows:
//   - the FN_<name> constant
//   - par_<name>_entry as the only function (no conts)
//   - aot_program_<name>_dispatch + aot_program_<name>_register
//   - body uses the iter-1 stub fallback because identity isn't
//     an App-of-Mat shape -- the emit returns NUM(0) regardless
//     of input.  That's fine for the outer-scaffolding demo;
//     real defs hit one of the recognised body shapes.
//
// Regenerate via: bash docs/aot_emitted_examples/_gen.sh

// auto-generated by thvm_aot_emit_program("identity_lam")
// def_id 0, arity 1, 0 cont(s)
//
// This source is meant to be #include'd into a TU that has
// already brought the thvm AOT runtime into scope (typically
// via `#include "src/thvm.c"` -- which transitively pulls in
// task.h / halloc.h / cont.c / resolve.c / worker.c).  The
// emit deliberately omits #includes so the same string works
// for both the in-tree path (test files) and the dylib path
// (a generated wrapper file that includes thvm.c at the top).

#define FN_identity_lam  0u

static AotResult par_identity_lam_entry(AotProgram *p, AotTask *t);

static AotResult par_identity_lam_entry(AotProgram *p, AotTask *t) {
  (void)p; (void)t;
  /* unrecognised body shape (iter 5) -- stub return */
  return aot_make_value(term_new(0, TAG_NUM, DT_INT32, 0));
}

static AotResult aot_program_identity_lam_dispatch(AotProgram *p, AotTask *t) {
  switch (t->fn_id) {
    case FN_identity_lam:  return par_identity_lam_entry(p, t);
    default:     return aot_make_value(0);
  }
}

fn void aot_program_identity_lam_register(AotProgram *p) {
  p->dispatch = aot_program_identity_lam_dispatch;
}
