// docs/aot_emitted_examples/tree_sum.c
//
// tree_sum: collapses a binary tree of NUM leaves into the sum.
// Bend2-style:
//   sum(leaf{v})    = v
//   sum(node{l, r}) = sum(l) + sum(r)
// 
// Shows:
//   - dead-arm pruning (CTR-only chain)
//   - leaf arm: TLam[v, v] -> args[0] inlined directly
//   - node arm: TLam[l, TLam[r, ...]] -> binds l = term_ctr_at(dv, 0),
//     r = term_ctr_at(dv, 1) (multi-LAM CTR destructure)
//   - sibling-pair TOp2 -> aot_alloc_cont + aot_make_split
//   - OP2 fold cont: lv + rv constant-folded from OP_ADD
//   - dispatch table: FN_tree_sum + CONT_tree_sum_0
// 
// Pairs with tree_build below; together they're the canonical
// fork-friendly workload Bend2 uses to demo MT scaling.
//
// Regenerate via: bash docs/aot_emitted_examples/_gen.sh

// auto-generated by thvm_aot_emit_program("tree_sum")
// def_id 0, arity 1, 1 cont(s)
//
// This source is meant to be #include'd into a TU that has
// already brought the thvm AOT runtime into scope (typically
// via `#include "src/thvm.c"` -- which transitively pulls in
// task.h / halloc.h / cont.c / resolve.c / worker.c).  The
// emit deliberately omits #includes so the same string works
// for both the in-tree path (test files) and the dylib path
// (a generated wrapper file that includes thvm.c at the top).

#define FN_tree_sum  0u
#define CONT_tree_sum_0  1u

static AotResult par_tree_sum_entry(AotProgram *p, AotTask *t);
static AotResult par_tree_sum_cont_0(AotProgram *p, AotTask *t);

static AotResult par_tree_sum_cont_0(AotProgram *p, AotTask *t) {
  (void)p;
  /* OP2 fold (op id 0) -- assumes both child results are NUM */
  u32 lv = (u32)term_val(t->args[0]);
  u32 rv = (u32)term_val(t->args[1]);
  return aot_make_value(
      term_new(0, TAG_NUM, term_ext(t->args[0]), lv + rv));
}

static AotResult par_tree_sum_entry(AotProgram *p, AotTask *t) {
  (void)p; (void)t;
  /* dispatch on t->args[0] (Phase 2 iter 5) */
  Term dv = wnf(t->args[0]);
  /* dead-arm pruned: chain is CTR-only (some arm destructures) */
  if (term_tag(dv) == TAG_CTR && term_ext(dv) == 0u) {
    return aot_make_value(term_ctr_at(dv, 0));
  }
  if (term_tag(dv) == TAG_CTR && term_ext(dv) == 1u) {
    u64 dp = aot_alloc_cont(CONT_tree_sum_0, 0, t->ret);
    return aot_make_split(
        aot_make_task(FN_tree_sum, aot_enc_ret((u32)dp, 0), term_ctr_at(dv, 0), 0, 0, 0),
        aot_make_task(FN_tree_sum, aot_enc_ret((u32)dp, 1), term_ctr_at(dv, 1), 0, 0, 0));
  }
  /* default arm */
  return aot_make_value(term_new(0, TAG_ERA, 0, 0));
}

static AotResult aot_program_tree_sum_dispatch(AotProgram *p, AotTask *t) {
  switch (t->fn_id) {
    case FN_tree_sum:  return par_tree_sum_entry(p, t);
    case CONT_tree_sum_0:  return par_tree_sum_cont_0(p, t);
    default:     return aot_make_value(0);
  }
}

fn void aot_program_tree_sum_register(AotProgram *p) {
  p->dispatch = aot_program_tree_sum_dispatch;
}
