// docs/aot_emitted_examples/tree_build.c
//
// Bend2-style tree builder.  Returns a binary tree of depth
// args[0] = d, with leaves carrying args[1] = x.  Source matches
// TinyHVM/resources/gists/par_tree_sum_bend2_compiled.c's
// `build` def (same fork shape, different surface syntax).
// 
// Shows:
//   - default-arm TLam destructure (binds `dd` to dv -- the
//     matched value, since this is the chain's catch-all)
//   - sibling-pair TCtr2 -> aot_alloc_cont + aot_make_split,
//     cont wraps in aot_make_ctr2(2u, t->args[0], t->args[1])
//     (the `node{l, r}` reassembly)
//   - 2-arity self-call via aot_make_task(FN_tree_build, ...)
//   - DP* construction with shared runtime cells: `dd` and `x`
//     are each used twice in the node{} arm, so auto-dup wraps
//     them into TAG_DP0/TAG_DP1.  The emit memoizes by source
//     dup_loc, so DP0 and DP1 of the SAME source dup share ONE
//     runtime cell (named dup_K_loc) -- Bend2 sharing semantics,
//     matches the hand-coded reference programs
//   - Dispatch forces dv = wnf(t->args[0]) so DP-wrapped CTRs
//     unwrap before the tag check fires
//
// Regenerate via: bash docs/aot_emitted_examples/_gen.sh

// auto-generated by thvm_aot_emit_program("tree_build")
// def_id 0, arity 2, 1 cont(s)
//
// This source is meant to be #include'd into a TU that has
// already brought the thvm AOT runtime into scope (typically
// via `#include "src/thvm.c"` -- which transitively pulls in
// task.h / halloc.h / cont.c / resolve.c / worker.c).  The
// emit deliberately omits #includes so the same string works
// for both the in-tree path (test files) and the dylib path
// (a generated wrapper file that includes thvm.c at the top).

#define FN_tree_build  0u
#define CONT_tree_build_0  1u

static AotResult par_tree_build_entry(AotProgram *p, AotTask *t);
static AotResult par_tree_build_cont_0(AotProgram *p, AotTask *t);

static AotResult par_tree_build_cont_0(AotProgram *p, AotTask *t) {
  (void)p;
  return aot_make_value(aot_make_ctr2(2u, t->args[0], t->args[1]));
}

static AotResult par_tree_build_entry(AotProgram *p, AotTask *t) {
  (void)p; (void)t;
  /* dispatch on t->args[0] (Phase 2 iter 5) */
  Term dv = wnf(t->args[0]);
  if (term_tag(dv) == TAG_NUM && (u32)term_val(dv) == 0u) {
    u64 dup_0_loc = aot_heap_alloc(1);
    heap_set(dup_0_loc, t->args[1]);
    Term v_2 = term_new(0, TAG_DP1, 65537, dup_0_loc);
    u64 dup_1_loc = aot_heap_alloc(1);
    heap_set(dup_1_loc, v_2);
    Term v_1 = term_new(0, TAG_DP1, 65538, dup_1_loc);
    Term v_0 = aot_make_ctr1(1, v_1);
    return aot_make_value(v_0);
  }
  if (term_tag(dv) == TAG_CTR && term_ext(dv) == 0u) {
    u64 dup_2_loc = aot_heap_alloc(1);
    heap_set(dup_2_loc, t->args[1]);
    Term v_6 = term_new(0, TAG_DP1, 65537, dup_2_loc);
    u64 dup_3_loc = aot_heap_alloc(1);
    heap_set(dup_3_loc, v_6);
    Term v_5 = term_new(0, TAG_DP1, 65538, dup_3_loc);
    Term v_4 = aot_make_ctr1(1, v_5);
    return aot_make_value(v_4);
  }
  /* default arm */
  u64 dup_4_loc = aot_heap_alloc(1);
  heap_set(dup_4_loc, dv);
  Term v_8 = term_new(0, TAG_DP1, 65536, dup_4_loc);
  u64 dup_5_loc = aot_heap_alloc(1);
  heap_set(dup_5_loc, t->args[1]);
  Term v_11 = term_new(0, TAG_DP1, 65537, dup_5_loc);
  u64 dup_6_loc = aot_heap_alloc(1);
  heap_set(dup_6_loc, v_11);
  Term v_10 = term_new(0, TAG_DP0, 65538, dup_6_loc);
  Term v_13 = term_new(0, TAG_DP0, 65536, dup_4_loc);
  Term v_14 = term_new(0, TAG_DP0, 65537, dup_5_loc);
  u64 dp = aot_alloc_cont(CONT_tree_build_0, 0, t->ret);
  return aot_make_split(
      aot_make_task(FN_tree_build, aot_enc_ret((u32)dp, 0), v_8, v_10, 0, 0),
      aot_make_task(FN_tree_build, aot_enc_ret((u32)dp, 1), v_13, v_14, 0, 0));
}

static AotResult aot_program_tree_build_dispatch(AotProgram *p, AotTask *t) {
  switch (t->fn_id) {
    case FN_tree_build:  return par_tree_build_entry(p, t);
    case CONT_tree_build_0:  return par_tree_build_cont_0(p, t);
    default:     return aot_make_value(0);
  }
}

fn void aot_program_tree_build_register(AotProgram *p) {
  p->dispatch = aot_program_tree_build_dispatch;
}
