// tools/bench_twee.c -- stage 7.4d Twee comparison harness.
//
// For each `.pr` file in `tests/data/atp/`:
//   1. Parses via `wald_parse_file`.
//   2. Emits a temporary TPTP-UEQ representation
//      (`cnf(...)` syntax) to `build/bench_twee_<name>.tptp`.
//   3. Invokes Twee via `popen()`, captures stdout +
//      wall-clock.
//   4. Writes a row to `build/bench-twee.csv`.
//
// Build:   cc -std=c11 -O2 -o build/bench_twee tools/bench_twee.c
// Run:     build/bench_twee [twee-path]
//          (default twee-path: ~/.cabal/bin/twee)

#include "../src/thvm.c"
#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>

#define MAX_FILES 64
#define PATH_LEN  256

// === TPTP emission =================================================
//
// Walk a Term recursively and write TPTP-CNF.  Variables (TAG_FVR)
// emit as "X0", "X1", ...  Constructors emit as "c<label>(args)" or
// "c<label>" for nullary -- we don't have access to the original
// symbol names from `WaldSpec` cheaply (the symbol table maps
// label -> name, so we look it up there).

static const WaldSpec *g_emit_spec = NULL;

// Find the human-readable name for a CTR label by walking
// spec->symbols[].  Returns NULL if not found.
static const char *spec_name_for_label(const WaldSpec *spec, u32 label) {
  for (u32 i = 0; i < spec->n_symbols; i++) {
    if (spec->symbols[i].label == label) return spec->symbols[i].name;
  }
  return NULL;
}

static void emit_term(FILE *f, Term t) {
  switch (term_tag(t)) {
    case TAG_FVR:
      fprintf(f, "X%u", term_ext(t));
      return;
    case TAG_CTR: {
      u32 lab = term_ext(t);
      u32 n   = term_ctr_n(t);
      const char *nm = spec_name_for_label(g_emit_spec, lab);
      if (nm) fprintf(f, "%s", nm);
      else    fprintf(f, "c%u", lab);
      if (n == 0) return;
      fprintf(f, "(");
      for (u32 i = 0; i < n; i++) {
        if (i) fprintf(f, ", ");
        emit_term(f, term_ctr_at(t, i));
      }
      fprintf(f, ")");
      return;
    }
    default:
      fprintf(f, "?T%u", term_tag(t));
      return;
  }
}

// Write a `.tptp` file representing the parsed spec as a
// TPTP-CNF problem.  Returns 0 on success.
static int write_tptp(const char *out_path, const WaldSpec *spec) {
  FILE *f = fopen(out_path, "w");
  if (f == NULL) return -1;
  g_emit_spec = spec;

  fprintf(f, "%% Auto-generated by tools/bench_twee.c\n");
  fprintf(f, "%% Source: %s\n\n", spec->name);

  for (u32 i = 0; i < spec->n_eqns; i++) {
    fprintf(f, "cnf(eqn%u, axiom, ", i);
    emit_term(f, spec->eqn_lhs[i]);
    fprintf(f, " = ");
    emit_term(f, spec->eqn_rhs[i]);
    fprintf(f, ").\n");
  }

  if (spec->goal_lhs != 0) {
    fprintf(f, "cnf(goal, negated_conjecture, ");
    emit_term(f, spec->goal_lhs);
    fprintf(f, " != ");
    emit_term(f, spec->goal_rhs);
    fprintf(f, ").\n");
  }

  fclose(f);
  return 0;
}

// === Twee invocation ================================================
//
// Run `<twee_path> --quiet --no-proof --max-cps <budget> <tptp>`
// and capture stdout into a buffer.  Returns the wall-clock ms.

static double run_twee(const char *twee_path, const char *tptp_path,
                      u32 max_cps, char *out, u32 cap) {
  char cmd[1024];
  snprintf(cmd, sizeof cmd,
           "%s --quiet --no-proof --max-cps %u '%s' 2>&1",
           twee_path, max_cps, tptp_path);
  struct timespec t0, t1;
  clock_gettime(CLOCK_MONOTONIC, &t0);
  FILE *p = popen(cmd, "r");
  if (p == NULL) {
    snprintf(out, cap, "popen failed");
    clock_gettime(CLOCK_MONOTONIC, &t1);
    return 0.0;
  }
  u32 w = 0;
  while (w + 1 < cap) {
    int c = fgetc(p);
    if (c == EOF) break;
    out[w++] = (char)c;
  }
  out[w] = 0;
  pclose(p);
  clock_gettime(CLOCK_MONOTONIC, &t1);
  return (t1.tv_sec - t0.tv_sec) * 1e3
       + (t1.tv_nsec - t0.tv_nsec) / 1e6;
}

// Parse Twee's stdout into a status string.  Twee prints
// "Theorem proved" / "GaveUp" / similar markers when run with
// `--quiet`.
static const char *parse_twee_status(const char *out) {
  if (strstr(out, "Theorem proved")) return "PROVED";
  if (strstr(out, "Theorem is true")) return "PROVED";
  if (strstr(out, "RESULT: Theorem")) return "PROVED";
  if (strstr(out, "GaveUp"))           return "TIMEOUT";
  if (strstr(out, "Ran out of"))       return "TIMEOUT";
  if (strstr(out, "ResourceOut"))      return "TIMEOUT";
  if (strstr(out, "Saturated"))        return "SATURATED";
  if (strstr(out, "Unsatisfiable"))    return "PROVED";
  return "UNKNOWN";
}

int main(int argc, char **argv) {
  thvm_init();

  const char *twee_path = (argc > 1) ? argv[1]
                          : "/Users/swish/.cabal/bin/twee";

  mkdir("build", 0755);

  FILE *csv = fopen("build/bench-twee.csv", "w");
  if (csv == NULL) {
    fprintf(stderr, "could not open build/bench-twee.csv\n");
    return 1;
  }
  fprintf(csv, "file,status,wall_ms,twee_output_head\n");

  DIR *dir = opendir("tests/data/atp");
  if (dir == NULL) {
    fprintf(stderr, "tests/data/atp not found\n");
    fclose(csv);
    return 1;
  }

  char files[MAX_FILES][PATH_LEN];
  u32 n_files = 0;
  struct dirent *de;
  while ((de = readdir(dir)) != NULL) {
    const char *name = de->d_name;
    size_t len = strlen(name);
    if (len < 4) continue;
    if (strcmp(name + len - 3, ".pr") != 0) continue;
    if (n_files >= MAX_FILES) continue;
    snprintf(files[n_files], PATH_LEN, "tests/data/atp/%s", name);
    n_files++;
  }
  closedir(dir);

  // Sort.
  for (u32 i = 1; i < n_files; i++) {
    for (u32 j = i; j > 0 && strcmp(files[j - 1], files[j]) > 0; j--) {
      char tmp[PATH_LEN];
      memcpy(tmp, files[j - 1], PATH_LEN);
      memcpy(files[j - 1], files[j], PATH_LEN);
      memcpy(files[j], tmp, PATH_LEN);
    }
  }

  // Match our ATP's step budget so the comparison is fair.
  const u32 BUDGET = 256;

  for (u32 i = 0; i < n_files; i++) {
    WaldSpec *spec = wald_init();
    WaldErr e = wald_parse_file(files[i], spec);
    if (e != WALD_OK) {
      fprintf(csv, "%s,PARSE_FAIL,0,\n", files[i]);
      wald_free(spec);
      continue;
    }

    char tptp_path[PATH_LEN];
    snprintf(tptp_path, PATH_LEN, "build/bench_twee_%u.tptp", i);
    write_tptp(tptp_path, spec);

    static char out[16384];
    double ms = run_twee(twee_path, tptp_path, BUDGET, out, sizeof out);

    const char *status = parse_twee_status(out);

    // Strip newlines / commas from the head of out for safe CSV
    // embedding.
    char head[256] = {0};
    u32 hi = 0;
    for (u32 j = 0; out[j] != 0 && hi + 1 < sizeof head; j++) {
      char c = out[j];
      if (c == '\n' || c == '\r' || c == ',') c = ' ';
      head[hi++] = c;
    }
    head[hi] = 0;

    fprintf(csv, "%s,%s,%.3f,%s\n", files[i], status, ms, head);
    fflush(csv);

    fprintf(stderr, "%s -> %s (%.3f ms)\n", files[i], status, ms);

    wald_free(spec);
  }

  fclose(csv);
  thvm_free();
  return 0;
}
