#!/usr/bin/env python3
# tools/embed_blob.py
#
# Generate a tiny C source + an inline assembly file that embeds
# a binary blob via the assembler's .incbin directive.  Much faster
# to compile and ~6x smaller on disk than encoding every byte as
# `0xNN, ` in C.  Used to bake the flattened thvm.c source into
# THVMLink.dylib (and standalone test binaries) so the AOT compile
# pipeline doesn't depend on src/ being on disk at run time.
#
# Output: a single .c file with both:
#   - extern symbols + length declarations
#   - an inline asm block that references the binary via .incbin,
#     wrapped in __asm__ at file scope so the assembler emits the
#     bytes into __DATA section.  Trailing NUL byte makes the data
#     usable as a C string.
#
# Usage:
#   python3 tools/embed_blob.py <input> <symbol_name> [format] > out.c
#
# `format` is the target object format: `macho` (default, Apple),
# `elf` (Linux), or `coff` (Windows).  It selects the section
# directive and whether the assembler symbol carries a leading `_`.
# This matters for the cross-compiled paclet libraries: the blob is
# linked into every per-platform THVMLink library, and the .incbin
# host object must match the linker's expected format.
#
# `<input>` path is recorded into the .c file as a STRING and the
# C compiler resolves it relative to its CWD at build time.  Pass
# an absolute path if your build uses out-of-tree builds.

import sys
import os

# Per-format (section-directive, leading-underscore?).  Mach-O and
# 32-bit COFF prefix C symbols with `_`; ELF and 64-bit COFF do not
# (all our COFF targets are x86-64, so no prefix there).
FORMATS = {
    'macho': ('.section __DATA,__const', True),
    'elf':   ('.section .rodata', False),
    'coff':  ('.section .rdata,"dr"', False),
}


def main():
    if len(sys.argv) not in (3, 4):
        sys.stderr.write('usage: embed_blob.py <input> <symbol_name> [macho|elf|coff]\n')
        sys.exit(1)
    blob_path = sys.argv[1]
    sym = sys.argv[2]
    fmt = sys.argv[3] if len(sys.argv) == 4 else 'macho'
    if fmt not in FORMATS:
        sys.stderr.write('embed_blob.py: unknown format {!r}\n'.format(fmt))
        sys.exit(1)
    section, underscore = FORMATS[fmt]
    # The section directive is embedded inside a C string literal, so any
    # quotes it carries (COFF's `"dr"` flags) must be backslash-escaped.
    section = section.replace('"', '\\"')
    n = os.path.getsize(blob_path)
    prefix = '_' if underscore else ''
    asm_sym = prefix + sym
    asm_len_sym = prefix + sym + '_len'

    sys.stdout.write(
        '// Auto-generated by tools/embed_blob.py from {} (format: {})\n'
        '// {} bytes + 1 NUL terminator embedded via assembler .incbin.\n\n'
        '#include <stddef.h>\n'
        '#include <stdint.h>\n\n'
        'extern const char {}[];\n'
        'extern const uint64_t {}_len;\n\n'
        '__asm__(\n'
        '    "{}\\n"\n'
        '    ".globl {}\\n"\n'
        '    "{}:\\n"\n'
        '    ".incbin \\"{}\\"\\n"\n'
        '    ".byte 0\\n"\n'
        '    ".globl {}\\n"\n'
        '    ".p2align 3\\n"\n'
        '    "{}:\\n"\n'
        '    ".quad {}\\n"\n'
        ');\n'
        .format(blob_path, fmt, n, sym, sym,
                section, asm_sym, asm_sym, blob_path,
                asm_len_sym, asm_len_sym, n)
    )


if __name__ == '__main__':
    main()
