#!/usr/bin/env python3
# tools/embed_blob.py
#
# Generate a tiny C source + an inline assembly file that embeds
# a binary blob via the assembler's .incbin directive.  Much faster
# to compile and ~6x smaller on disk than encoding every byte as
# `0xNN, ` in C.  Used to bake the flattened thvm.c source into
# THVMLink.dylib (and standalone test binaries) so the AOT compile
# pipeline doesn't depend on src/ being on disk at run time.
#
# Output: a single .c file with both:
#   - extern symbols + length declarations
#   - an inline asm block that references the binary via .incbin,
#     wrapped in __asm__ at file scope so the assembler emits the
#     bytes into __DATA section.  Trailing NUL byte makes the data
#     usable as a C string.
#
# Usage:
#   python3 tools/embed_blob.py <input> <symbol_name> > out.c
#
# `<input>` path is recorded into the .c file as a STRING and the
# C compiler resolves it relative to its CWD at build time.  Pass
# an absolute path if your build uses out-of-tree builds.

import sys
import os


def main():
    if len(sys.argv) != 3:
        sys.stderr.write('usage: embed_blob.py <input> <symbol_name>\n')
        sys.exit(1)
    blob_path = sys.argv[1]
    sym = sys.argv[2]
    n = os.path.getsize(blob_path)
    # macOS: symbols are prefixed with `_` in assembly.
    asm_sym = '_' + sym
    asm_len_sym = '_' + sym + '_len'

    sys.stdout.write(
        '// Auto-generated by tools/embed_blob.py from {}\n'
        '// {} bytes + 1 NUL terminator embedded via assembler .incbin.\n\n'
        '#include <stddef.h>\n'
        '#include <stdint.h>\n\n'
        'extern const char {}[];\n'
        'extern const uint64_t {}_len;\n\n'
        '__asm__(\n'
        '    ".section __DATA,__const\\n"\n'
        '    ".globl {}\\n"\n'
        '    "{}:\\n"\n'
        '    ".incbin \\"{}\\"\\n"\n'
        '    ".byte 0\\n"\n'
        '    ".globl {}\\n"\n'
        '    ".p2align 3\\n"\n'
        '    "{}:\\n"\n'
        '    ".quad {}\\n"\n'
        ');\n'
        .format(blob_path, n, sym, sym,
                asm_sym, asm_sym, blob_path,
                asm_len_sym, asm_len_sym, n)
    )


if __name__ == '__main__':
    main()
